name: Build Test Workflow

on:
  workflow_dispatch:
    inputs:      
      servernames:        
        description: 'Comma-separated list of SQL Server names (e.g., SERVER1,SERVER2)'
        required: true
        default: 'F9NBPX3'
jobs:
    get-sql-instances:
        runs-on: [self-hosted, windows]
        steps:
          - name: Checkout repository
            # Step to checkout the repository
            # This is necessary to access the SQL scripts and other files in the repository
            uses: actions/checkout@v4

          - name: Setup PowerShell environment
            shell: powershell
            run: |
                Import-Module dbatools

          - name: Get-SQL-Server-instances
            # Step to set up the PowerShell environment
            shell: powershell
            run: |
              $servernames = "${{ github.event.inputs.servernames }}" -split ','
              Write-Host "============================================================"
              Write-Host "Getting SQL Server instances for ${servernames}"
              foreach ($server in $servernames) {
                # Loop through each server name provided in the input
                Write-Host "Processing server: $server"
                try {
                $instances = Get-DbaService -ComputerName $server -Type Engine -EnableException |
                Select-Object @{L='SqlInstance';e={('{0}\{1}' -f $_.ComputerName, $_.InstanceName)}}
                Write-Host "SQL Server instances found:"
                $instances
                Write-Host "============================================================"                
                } catch {
                Write-Host "Error: Failed to get SQL Server instances for ${server}."
                Write-Host "Exception Message: $($_.Exception.Message)"
                Write-Host "Exception Details: $($_ | Out-String)"
                exit 1
                }
                }           
          - name: Invoke-Check-DefaultPath
            shell: powershell
            run: |
                foreach ($instance in $instances) {
                    # Loop through each server name provided in the input
                    Write-Host "Processing server: $instance"
                    Write-Host "Checking defaultpath on: $instance"
                }
          - name: Invoke-Check-MaxServerMemory
            shell: powershell
            run: |
                foreach ($instance in $instances) {
                    # Loop through each server name provided in the input
                    Write-Host "Processing server: $instance"
                    Write-Host "Checking memory on: $instance"
                }
