name: Testing Worklow

# Controls when the workflow will run, e.g. manually
on: workflow_dispatch
inputs:
  sqinstancenames:
    description: 'Comma-separated list of SQL Server instance names (e.g., SERVER1,SERVER2)'
    required: true
    default: 'F9NBPX3\SQL2019'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  first-job:
    runs-on: [self-hosted, windows]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Run 1-CreatePeerCheckTable.sql on all instances
        shell: powershell
        run: |
          Write-Host "Input: sqinstancenames = ${{ github.event.inputs.sqinstancenames }}"
          $instance = "${{ github.event.inputs.sqinstancenames }}" -split ','
          Write-Host "============================================================"
          Write-Host "Running 1-CreatePeerCheckTable.sql on ${instance}"
            $query = Get-Content -Raw -Path "${env:GITHUB_WORKSPACE}\Peer Check\1-CreatePeerCheckTable.sql"
          try {
            Invoke-DbaQuery -SqlInstance $instance -Query $query -EnableException
            Write-Host "1-CreatePeerCheckTable.sql executed successfully on ${instance}"
            Write-Host "============================================================"
          } catch {
            Write-Host "Error: Failed to run 1-CreatePeerCheckTable.sql on ${instance}."
            Write-Host "Exception Message: $($_.Exception.Message)"
            Write-Host "Exception Details: $($_ | Out-String)"
            exit 1
          }
