name: Testing Variables

# Controls when the workflow will run, e.g. manually
on:
  workflow_dispatch:
    inputs:      
      sqinstancenames:        
        description: 'Comma-separated list of SQL Server instance names (e.g., SERVER1,SERVER2)'
        required: true
        default: 'F9NBPX3\SQL2019'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  first-job:
    runs-on: windows-latest
    env:
      # Set environment variables from the input
      # This allows the job to access the input values as environment variables
        INSTANCELIST: ${{ github.event.inputs.sqinstancenames }}
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Print all environment variables
          shell: powershell
          run: |
            Get-ChildItem Env:
        - name: Show INSTANCELIST
          shell: powershell
          run: |
            Write-Host "INSTANCELIST value: $env:INSTANCELIST"



        